### ISSUE TITLE
Use schematics for installation steps 

### ISSUE THREAD

**Issue by meltedspark** [meltedspark/angular-builders#22]
_From @meltedspark on August 13, 2018 14:40_

The following should be done automatically with [schematics](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2) instead of requiring the user to do it manually:
1. Removing Karma related stuff
2. Updating Typescript configs
3. Updating _angular.json_ 

_Copied from original issue: angular-builders/jest#3_

**Comment by davinkevin** [comment]
I've developed [some schematics](https://github.com/davinkevin/jest) doing this. I was about to develop my own builder for this when I find your project. We maybe can do something together...?

**Comment by meltedspark** [comment]
Sure, you're more than welcome to make a PR for this!  
You'll have to modify your schematics a bit (as it should change _angular.json_ instead _package.json_).  
It's also unnecessary to create Jest setup files (they are already included in the builder) and install Jest (as it is just a builder).  
Basically the schematics for this builder would have to do the installations steps (except for step 1) described in the [README](https://github.com/meltedspark/angular-builders/blob/master/packages/jest/README.md).  
If you're up to implementing this, please go ahead!

**Comment by meltedspark** [comment]
I would say that such a PR should contain an end-to-end test of installing the library, configuring the project using schematics and running the tests, but if it is too much I can handle this part.

**Comment by meltedspark** [comment]
@davinkevin Shall I take it from here or you'd like to implement that?

**Comment by davinkevin** [comment]
You can take it... I don't have time to do this sadly. 😓
Sorry

**Comment by froko** [comment]
I've actually made a schematic which includes your jest-builder. It can be found here: [https://github.com/froko/ng-essentials](https://github.com/froko/ng-essentials)

Any feedback is highly welcome!

**Comment by meltedspark** [comment]
@froko Great work! I think it is a great initiative! 
Do you think it's possible for you to create a PR with the same functionality here? To make it all-in-one solution, so that one could simply run `ng add @angular-builders/jest`?  
If not, would you mind me borrowing your source code and adding it here myself (with copyright of course)?

**Comment by asnowwolf** [comment]
Thank you for your great work. @froko @just-jeb 
When will this feature be available? It took me ten minutes to finish it manually today. If you can provide a schematics, my work efficiency will increase 300 times. 😁

**Comment by schuchard** [comment]
Hi everyone, I've updated the [`@briebug/jest-schematic`](https://github.com/briebug/jest-schematic/tree/599664e777f3d88393d33ebbc02086f3cdcf7ffb) to utilize this builder and support single and multi app/lib workspaces. It's published under a pre-release right now and can be installed at:
```bash
ng add @briebug/jest-schematic@3.0.0-0
```

Feedback is welcome.

**Comment by just-jeb** [comment]
@schuchard what do you think about adding this schematics as part of the builder? So that you could just run `ng add @angular-builders/jest`?

**Comment by just-jeb** [comment]
# Issue #22 Implementation Plan: Angular Schematics for Installation Steps

## Overview
Replace manual installation steps (removing Karma, updating TS configs, updating angular.json) with automated Angular schematics, including ng-update migrations for version upgrades.

## Research Findings

### What is ng-update?
`ng-update` is Angular's standard migration mechanism for automating breaking changes during package upgrades. When a user runs `ng update @angular-builders/<package>`, the CLI:
1. Reads the package's `ng-update` metadata from `package.json`
2. Executes migration schematics for version ranges the user is upgrading through
3. Transforms code, configs, and dependencies automatically

### Angular's ng-update Metadata Format
The `package.json` `ng-update` field specifies:
```json
{
  "ng-update": {
    "packageGroup": ["@angular-builders/*"],
    "migrations": "./schematics/migrations.json"
  }
}
```

The `migrations.json` file lists version-keyed schematics that apply when upgrading through that version range.

### What Migrations Should Cover (Based on Angular Ecosystem Patterns)

#### 1. **Initial Installation Schematic** (`ng add`)
- Runs on initial package install (e.g., `ng add @angular-builders/custom-webpack`)
- Should:
  - Update `angular.json` to add the builder configuration
  - Remove Karma configuration (for Jest builder)
  - Update `tsconfig.json` if needed
  - Offer configuration prompts (e.g., which builder to default to)

#### 2. **Version Migration Schematics** (`ng update`)
- Runs when user upgrades between major/minor versions
- Should:
  - Update schema field names if builders' APIs change
  - Migrate deprecated options to new ones
  - Update peer dependency version ranges
  - Update example configs in comments
  - Handle breaking changes in builder options

#### 3. **Cross-Package Consistency**
- All builders (`custom-esbuild`, `custom-webpack`, `jest`, `bazel`, `timestamp`) should have consistent:
  - Schematic names and locations
  - Configuration transformation patterns
  - Error handling and logging
  - Migration order and dependencies

## Implementation Strategy

### Phase 1: Foundation (Schematic Scaffolding)
- [ ] Add `@angular-devkit/schematics` and `@angular/devkit/schematics` to common devDependencies
- [ ] Create `packages/common/schematics/` directory with shared utilities:
  - JSON file manipulation helpers (update angular.json, tsconfig.json, package.json)
  - Logging and error handling utilities
  - Common option schema definitions
- [ ] Document patterns in `packages/common/AGENTS.md` under new "Schematics" section

### Phase 2: Per-Package ng-add Schematics (Initial Install)
- [ ] **jest builder:**
  - Remove Karma: delete `karma.conf.js` + update `angular.json` (remove karma test builder)
  - Add Jest: add `@angular-builders/jest:test` builder to projects in `angular.json`
  - Update `tsconfig.spec.json`: change `types: ["jasmine"]` → `types: ["jest"]`
  - Offer prompt: "Default to Jest for all test projects?" (batch-update if yes)

- [ ] **custom-webpack builder:**
  - Add `@angular-builders/custom-webpack:build` option to `angular.json`
  - Add webpack config file template (`webpack.config.js` or project-specific)
  - Offer prompt: "Which projects should use custom-webpack?"

- [ ] **custom-esbuild builder:**
  - Add `@angular-builders/custom-esbuild:build` option to `angular.json`
  - Add esbuild config template
  - Offer prompt: "Which projects should use custom-esbuild?"

- [ ] **bazel, timestamp:**
  - Similar template patterns per builder

### Phase 3: Version Migration Schematics (ng-update)
- [ ] Create `migrations.json` in each package specifying version ranges
- [ ] Example structure:
  ```json
  {
    "schematics": {
      "migration-v20-to-v21": {
        "version": "21.0.0-beta.0",
        "description": "Migrate to Angular 21 builder APIs",
        "factory": "./migrate-v20-to-v21"
      }
    }
  }
  ```
- [ ] For each builder, write migration schematics handling:
  - Option name changes (`myOption` → `newOption`)
  - Deprecated option removal with warnings
  - Type transformations (e.g., string[] → {files: string[]})
  - Peer dependency version updates

### Phase 4: Update package.json Metadata
- [ ] Add `ng-update` to each builder's `package.json`:
  ```json
  {
    "ng-update": {
      "packageGroup": ["@angular-builders/common", "@angular-builders/<builder>"],
      "migrations": "./schematics/migrations.json"
    }
  }
  ```
- [ ] Update `builders.json` to reference ng-add schematic

### Phase 5: Testing
- [ ] Create integration tests in `packages/*/tests/` for:
  - ng-add schematic execution (fresh Angular project setup)
  - Migration execution (upgrade from previous version)
  - Config file correctness post-execution
- [ ] Use Angular's official [schematics test helpers](https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/test.ts)
- [ ] Test in example projects with real angular.json and tsconfig.json files

### Phase 6: Documentation
- [ ] Update each package's README with:
  - Installation via `ng add @angular-builders/<package>`
  - ng-update migration steps and what changes to expect
  - Manual fallback steps if schematic fails
- [ ] Add example migration scenarios (e.g., "upgrade from v18 to v21")

## Key Decisions Needed

1. **Prompts during ng-add:**
   - Jest builder: Should it default to all projects or ask per-project?
   - Webpack/ESBuild builders: Should users choose specific projects or default to all?

2. **Migration strategy for breaking changes:**
   - Auto-fix deprecated options or warn + require manual fix?
   - Example: If `myOption` was renamed to `newOption`, should we auto-migrate or require user action?

3. **Peer dependency handling:**
   - Should migrations auto-update `package.json` peer dependency ranges, or just warn?

4. **Backward compatibility:**
   - Support ng-add/ng-update for Angular 18+, or limit to 21+ (next major)?

## Success Criteria
- [ ] `ng add @angular-builders/<builder>` works in a fresh Angular 21 project
- [ ] `ng update @angular-builders/<builder>@next` executes migrations successfully
- [ ] All builder packages have consistent schematic behavior
- [ ] Integration tests pass for ng-add and ng-update workflows
- [ ] Documentation is clear and examples are runnable

## References
- [Angular Schematics Guide](https://angular.io/guide/schematics)
- [ng-update Official Docs](https://angular.io/guide/schematics-authoring-public-schematics#ng-update)
- [Angular CLI Migrations Example](https://github.com/angular/angular-cli/tree/main/packages/schematics)
- [Official Test Utilities](https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/test.ts)
